### ISSUE TITLE
Filedrop: Failed to resolve relay addresses. Failed to succefully (sic) dial any bootstrap node

### ISSUE THREAD

**Issue by Erudition** [dao-xyz/peerbit-examples#10]
The File Drop app has yet to work for me -- joining a space either never loads, or the space shows as empty despite the seeded files showing on the other device.

Test on Firefox and Chrome on Windows, as well as Firefox and Chrome on Android. Enterprise network.

```
aquire id at 0 index-JSApnn92.js:150:95174
Create client index-JSApnn92.js:180:4839
Ignoring inability to install OPFS sqlite3_vfs: Cannot install OPFS: Missing SharedArrayBuffer and/or Atomics. The server must emit the COOP/COEP response headers to enable those. See https://sqlite.org/wasm/doc/trunk/persistence.md#coop-coep sqlite3.worker.min-B-hRTo3R.js:4:15191
Create done index-JSApnn92.js:180:5287
C04FV3U1WA3NGbprbEnrBTa9YHhgSfTm49PiAd7T6/Q= index-JSApnn92.js:180:5314
Bootstrap start... index-JSApnn92.js:180:5748
Firefox can’t establish a connection to the server at wss://3df267fccbe9bb6b38c5ff5dde57f5401078b579.peerchecker.com:4003/p2p/12D3KooWN6xTJ8ZkRX4HZX4fa8NR9sDzMgoAxizwHMsDYSVpE7xy. index-JSApnn92.js:150:78536
Firefox can’t establish a connection to the server at wss://23a1839722ad07345186f20bd33110da13dc8d2e.peerchecker.com:4003/p2p/12D3KooWCHABWRzqR9iZQA8WzdNzSnELZVs7nwHmuJKWUYLQmoCM. index-JSApnn92.js:150:78536
Firefox can’t establish a connection to the server at wss://cc75656fce6cc671ffaf32bb795279a44ca0ec10.peerchecker.com:4003/p2p/12D3KooWSYTYuNbyfkTEXmoTbegpwWGUSrPPhmD9y7JqVfZv3AKs. index-JSApnn92.js:150:78536
Object { module: "client" }
 Failed to dial bootstrap address(s): "/dns4/23a1839722ad07345186f20bd33110da13dc8d2e.peerchecker.com/tcp/4003/wss/p2p/12D3KooWCHABWRzqR9iZQA8WzdNzSnELZVs7nwHmuJKWUYLQmoCM". Reason: CodeError: Could not connect to /dns4/23a1839722ad07345186f20bd33110da13dc8d2e.peerchecker.com/tcp/4003/wss/p2p/12D3KooWCHABWRzqR9iZQA8WzdNzSnELZVs7nwHmuJKWUYLQmoCM index-JSApnn92.js:113:254896
Object { module: "client" }
 Failed to dial bootstrap address(s): "/dns4/3df267fccbe9bb6b38c5ff5dde57f5401078b579.peerchecker.com/tcp/4003/wss/p2p/12D3KooWN6xTJ8ZkRX4HZX4fa8NR9sDzMgoAxizwHMsDYSVpE7xy". Reason: CodeError: Could not connect to /dns4/3df267fccbe9bb6b38c5ff5dde57f5401078b579.peerchecker.com/tcp/4003/wss/p2p/12D3KooWN6xTJ8ZkRX4HZX4fa8NR9sDzMgoAxizwHMsDYSVpE7xy index-JSApnn92.js:113:254896
Object { module: "client" }
 Failed to dial bootstrap address(s): "/dns4/cc75656fce6cc671ffaf32bb795279a44ca0ec10.peerchecker.com/tcp/4003/wss/p2p/12D3KooWSYTYuNbyfkTEXmoTbegpwWGUSrPPhmD9y7JqVfZv3AKs". Reason: CodeError: Could not connect to /dns4/cc75656fce6cc671ffaf32bb795279a44ca0ec10.peerchecker.com/tcp/4003/wss/p2p/12D3KooWSYTYuNbyfkTEXmoTbegpwWGUSrPPhmD9y7JqVfZv3AKs index-JSApnn92.js:113:254896
Failed to resolve relay addresses. Failed to succefully dial any bootstrap node index-JSApnn92.js:180:5645
Bootstrap done index-JSApnn92.js:180:5806
Source map error: Error: URL constructor:  is not a valid URL.
Resource URL: wasm:https://files.dao.xyz/assets/index-JSApnn92.js%20line%2040%20%3E%20WebAssembly.instantiate
Source Map URL: null
```

Could "peerchecker.com" be gone for good?

**Comment by marcus-pousette** [comment]
Most likely related to this issue 

 https://github.com/dao-xyz/peerbit/issues/284
 
 I fixed it now by restarting the servers, but I am trying to resolve this issue permantly

**Comment by Yeshey** [comment]
I might be seeing this in https://stream.dao.xyz/ as well:
```
index-Cjhdz6Hl.js:26 Failed to bootstrap: Error: Failed to succefully dial any bootstrap node
    at hf.bootstrap (index-Dyc8ML2f.js:43:26201)
    at async index-Cjhdz6Hl.js:26:19943
    at async q (index-Cjhdz6Hl.js:26:21188)
    at async index-Cjhdz6Hl.js:26:21475
```
